### ISSUE TITLE
Layout broken

### ISSUE THREAD

**Issue by zhil** [kendrick-k/symfony-debug-toolbar-git#14]
In symfony2.3.30 layout is broken. Yep, its very old, but vendors list in application is huge and nightmare vendor upgrade are still in progress.

![image](https://cloud.githubusercontent.com/assets/981783/19622042/04b1edd2-98a9-11e6-9300-aae80b9f54d5.png)

just wonder - is it only vendors issue?

**Comment by kendrick-k** [comment]
Hello ok, I've created a new version 1.4.4 with a shorter date, it should fix this ! Is this bundle (very) useful for you ?

**Comment by zhil** [comment]
Thanks. Yep, nice bundle, going to add few features too

**Comment by kendrick-k** [comment]
cool, you're welcome !
