### ISSUE TITLE
Use symfony-web-dir instead of hardcoded '../web'

### ISSUE THREAD

**Issue by stephanvierkant** [kendrick-k/symfony-debug-toolbar-git#19]
https://github.com/kendrick-k/symfony-debug-toolbar-git/blob/master/DataCollector/GitDataCollector.php#L38

This line assumes that the web dir is alway 'web', but it should use composer.json: `extra.symfony-web-dir`:

https://symfony.com/doc/current/configuration/override_dir_structure.html#override-the-web-directory

**Comment by kendrick-k** [comment]
Thanks, do you know how I could implement it ?

**Comment by kendrick-k** [comment]
hi @stephanvierkant !
