### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by Kevinrob** [kendrick-k/symfony-debug-toolbar-git#2]
Hi,  
when I execute phpunit and the project isn't in a git environement, I have a lot of:
`fatal: Not a git repository (or any of the parent directories): .git`  

Maybe we can test for a `.git` folder before doing the command?

**Comment by kendrick-k** [comment]
Hello, thanks, sure !

**Comment by kendrick-k** [comment]
Version 1.1 should fit : https://github.com/kendrick-k/symfony-debug-toolbar-git

**Comment by Kevinrob** [comment]
Thanks!
