### ISSUE TITLE
Feature to see all directories versioned by git

### ISSUE THREAD

**Issue by rafaelgfirmino** [kendrick-k/symfony-debug-toolbar-git#7]
Currently the toolbar only sees versioned directories in the root of application.
I like to discuss the viability of implement a feature to make the toolbar see all versioned packages. For example, some isolated bundles in other directories.
What do you think?

**Comment by kendrick-k** [comment]
Do you think of vendors also ?

**Comment by rafaelgfirmino** [comment]
Not yet.
Maybe in another issue.

**Comment by zhil** [comment]
@Rafaelgfirmino just wonder - will you finish your PR? I thought about the same features :)

**Comment by mediafigaro** [comment]
not sure ! go ahead :)
