### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by rafaelgfirmino** [kendrick-k/symfony-debug-toolbar-git#8]
We need to apply some improvements in the code before you make the changes to get catch any git repository.
I will apply the extract methods.

example:
 elseif (strpos($d, 'Author') === 0)  you get author commit,

 we would do something like:
$this->data['author'] = Git::shell('git log -1 --pretty=%an');
or
 $this->data['author'] = Git::shell(GitCommand::AUTOR_LAST_COMMIT):

What do you think ?

**Comment by kendrick-k** [comment]
ok it seems clean $this->data['author'] = Git::shell(GitCommand::AUTOR_LAST_COMMIT), by adding more git repo you think of which use case ?

**Comment by rafaelgfirmino** [comment]
I think we do not need many repositories.
But we must choose where this our main repository.

**Comment by rafaelgfirmino** [comment]
do not forget to look at the README

**Comment by kendrick-k** [comment]
Hi, can you check $date = $this->gitService->shellExec(GitCommand::GIT_COMMIT_DATE);
$dateCommit = date_create($date); I had a boolean false for this, so an exception on $time = date_diff($dateCommit, $dateNow);

ContextErrorException in GitDataCollector.php line 245:
Warning: date_diff() expects parameter 1 to be DateTimeInterface, boolean given

**Comment by kendrick-k** [comment]
Test must be reviewed I think : GitDataCollectorTest.php
https://travis-ci.org/kendrick-k/symfony-debug-toolbar-git/jobs/87541166

**Comment by kendrick-k** [comment]
README, more general : #example 1: github repository 
    repository_local_dir: https://github.com/team/project/commit/
#example 2: gitlab repository 
    repository_local_dir: https://gitlab.com/team/project/commit/
#example 3: bit repository 
    repository_local_dir: https://bitbucket.org/team/project/commits/

+
Case : if the git directory doesn't exists you will see this message

teste => test better ?
